---
kind: pipeline
type: kubernetes
name: frontend

# plop

steps:
## FRONTEND ###
- name: hello
  image: alpine
  commands:
  - echo hello

- name: bonjour
  image: alpine
  commands:
  - echo bonjour
