---
kind: pipeline
type: kubernetes
name: frontend

trigger:
  branch:
    - master
    - release/*
    - develop
  event:
    - push
    - pull_request
    - tag

steps:
- name: hello
  image: alpine
  commands:
  - echo hello

- name: bonjour
  image: alpine
  commands:
  - echo bonjour
